import type { DiscoveryQuestion } from "@music-rpg/shared";

/**
 * Sound Discovery, as data.
 *
 * Nothing here is screen logic: the flow renders whatever questions exist for
 * the player's audience, in order, and the inference engine reads the same
 * weights. Adding a question is a seed change and a test, not a new component.
 */
export const DISCOVERY_VERSION = 1;

export const discoveryQuestions: DiscoveryQuestion[] = [
  {
    id: "q_aux",
    version: DISCOVERY_VERSION,
    orderIndex: 10,
    prompt: "When someone gives you the AUX, what are you trying to do?",
    helpText: "There is no correct answer. Pick the one you'd actually do.",
    kind: "CHOICE",
    appliesTo: "BOTH",
    options: [
      {
        id: "move",
        label: "Make everyone move.",
        detail: "The room decides whether it worked.",
        weights: {
          sound: { melodicRhythmic: 0.4, intimateAnthemic: 0.35, darkBright: 0.2, accessibleExperimental: -0.3 },
          skills: { performance: 6, flow: 4 },
          psychology: { confidence: 5 },
          archetypes: { THE_PERFORMER: 3, THE_HITMAKER: 2 },
          traits: { SHOWMAN: 2 },
        },
      },
      {
        id: "listen",
        label: "Make everyone listen.",
        detail: "Quiet is a kind of attention.",
        weights: {
          sound: { minimalDense: -0.35, intimateAnthemic: -0.3, accessibleExperimental: 0.15 },
          skills: { lyricism: 6, storytelling: 5 },
          psychology: { patience: 6 },
          archetypes: { THE_STORYTELLER: 3, THE_ARCHITECT: 2 },
          traits: { CRATE_DIGGER: 2 },
        },
      },
      {
        id: "uncomfortable",
        label: "Make everyone uncomfortable.",
        detail: "Friction is the point.",
        weights: {
          sound: { accessibleExperimental: 0.5, darkBright: -0.4, rawPolished: -0.3 },
          skills: { experimentation: 8 },
          psychology: { riskTolerance: 8, ego: 3 },
          archetypes: { THE_DISRUPTOR: 4 },
          traits: { HEADSTRONG: 2 },
        },
      },
      {
        id: "feel",
        label: "Make everyone feel something.",
        detail: "Whatever it is, it should land.",
        weights: {
          sound: { intimateAnthemic: -0.2, melodicRhythmic: -0.35, darkBright: -0.1 },
          skills: { melody: 6, storytelling: 4 },
          psychology: { resilience: 3, patience: 4 },
          archetypes: { THE_STORYTELLER: 2, THE_VISIONARY: 1 },
        },
      },
      {
        id: "better",
        label: "Show everyone I'm better.",
        detail: "It's a competition whether they know it or not.",
        weights: {
          sound: { rawPolished: -0.2, melodicRhythmic: 0.25 },
          skills: { battleIQ: 8, flow: 5 },
          psychology: { competitiveness: 10, ego: 6 },
          archetypes: { THE_PURIST: 2, THE_DISRUPTOR: 1 },
          traits: { BATTLE_BORN: 3 },
        },
      },
    ],
  },
  {
    id: "q_matters",
    version: DISCOVERY_VERSION,
    orderIndex: 20,
    prompt: "What matters most?",
    helpText: "The thing you'd protect if you had to cut everything else.",
    kind: "CHOICE",
    appliesTo: "BOTH",
    options: [
      {
        id: "beat",
        label: "Beat.",
        detail: "The floor under everything.",
        weights: {
          sound: { melodicRhythmic: 0.45, minimalDense: 0.15, organicElectronic: 0.2 },
          skills: { production: 8 },
          archetypes: { THE_ARCHITECT: 2 },
          traits: { CRATE_DIGGER: 2 },
        },
      },
      {
        id: "bars",
        label: "Bars.",
        detail: "Say something that can't be said better.",
        weights: {
          sound: { melodicRhythmic: 0.2, rawPolished: -0.25, classicFuturistic: -0.3 },
          skills: { lyricism: 9, battleIQ: 4 },
          archetypes: { THE_PURIST: 3 },
          traits: { BATTLE_BORN: 1 },
        },
      },
      {
        id: "hook",
        label: "Hook.",
        detail: "The part they keep after they forget you.",
        weights: {
          sound: { accessibleExperimental: -0.4, melodicRhythmic: -0.3, rawPolished: 0.3, intimateAnthemic: 0.3 },
          skills: { melody: 9 },
          archetypes: { THE_HITMAKER: 4 },
          traits: { HITMAKER: 3 },
        },
      },
      {
        id: "story",
        label: "Story.",
        detail: "Somebody's life, told properly.",
        weights: {
          sound: { intimateAnthemic: -0.4, minimalDense: -0.2 },
          skills: { storytelling: 10 },
          psychology: { patience: 5 },
          archetypes: { THE_STORYTELLER: 4 },
        },
      },
      {
        id: "feeling",
        label: "Feeling.",
        detail: "Technique is downstream of it.",
        weights: {
          sound: { darkBright: -0.2, organicElectronic: -0.2, rawPolished: -0.15 },
          skills: { melody: 5, performance: 4 },
          psychology: { resilience: 4 },
          archetypes: { THE_VISIONARY: 2 },
        },
      },
    ],
  },
  {
    id: "q_challenged",
    version: DISCOVERY_VERSION,
    orderIndex: 30,
    prompt: "Someone challenges you publicly.",
    helpText: "Not hypothetically. This will happen in the Underground.",
    kind: "CHOICE",
    appliesTo: "BOTH",
    options: [
      {
        id: "immediate",
        label: "Respond immediately.",
        detail: "Silence reads as agreement.",
        weights: {
          sound: { rawPolished: -0.25 },
          skills: { battleIQ: 8, flow: 4 },
          psychology: { competitiveness: 10, patience: -8, riskTolerance: 5 },
          archetypes: { THE_DISRUPTOR: 2 },
          traits: { BATTLE_BORN: 4 },
        },
      },
      {
        id: "devastating",
        label: "Wait and make something devastating.",
        detail: "Time is a weapon.",
        weights: {
          sound: { minimalDense: -0.15, darkBright: -0.25 },
          skills: { lyricism: 6, battleIQ: 5 },
          psychology: { patience: 10, discipline: 6, competitiveness: 6 },
          archetypes: { THE_ARCHITECT: 2, THE_PURIST: 1 },
          traits: { PERFECTIONIST: 3 },
        },
      },
      {
        id: "laugh",
        label: "Laugh.",
        detail: "It costs them more than it costs you.",
        weights: {
          sound: { darkBright: 0.25 },
          skills: { performance: 5 },
          psychology: { confidence: 8, ego: 3, adaptability: 5 },
          archetypes: { THE_PERFORMER: 2 },
          traits: { SHOWMAN: 2 },
        },
      },
      {
        id: "ignore",
        label: "Ignore it.",
        detail: "Back to work.",
        weights: {
          sound: { intimateAnthemic: -0.2 },
          skills: { production: 4 },
          psychology: { discipline: 8, patience: 6, ego: -4 },
          archetypes: { THE_PURIST: 2, THE_ARCHITECT: 1 },
          traits: { WORKHORSE: 3 },
        },
      },
      {
        id: "hit",
        label: "Turn it into a hit.",
        detail: "Attention is fuel, not damage.",
        weights: {
          sound: { accessibleExperimental: -0.3, rawPolished: 0.25 },
          skills: { melody: 6, versatility: 5 },
          psychology: { adaptability: 10, ambition: 6 },
          archetypes: { THE_HITMAKER: 3, THE_CHAMELEON: 2 },
          traits: { HITMAKER: 2 },
        },
      },
    ],
  },
  {
    id: "q_environment",
    version: DISCOVERY_VERSION,
    orderIndex: 40,
    prompt: "Which environment feels most like your music?",
    helpText: "Where the work actually sounds like itself.",
    kind: "CHOICE",
    appliesTo: "BOTH",
    options: [
      {
        id: "bedroom",
        label: "Bedroom studio.",
        detail: "Headphones, late, nobody watching.",
        weights: {
          sound: { intimateAnthemic: -0.45, rawPolished: -0.2, minimalDense: -0.25, organicElectronic: 0.1 },
          skills: { production: 5, melody: 3 },
          psychology: { discipline: 5 },
          archetypes: { THE_ARCHITECT: 2 },
          traits: { WORKHORSE: 2 },
        },
      },
      {
        id: "basement",
        label: "Record-filled basement.",
        detail: "Dust, crates, lineage.",
        weights: {
          sound: { classicFuturistic: -0.5, organicElectronic: -0.45, rawPolished: -0.2 },
          skills: { production: 6, storytelling: 3 },
          archetypes: { THE_PURIST: 3 },
          traits: { CRATE_DIGGER: 4 },
        },
      },
      {
        id: "commercial",
        label: "Commercial studio.",
        detail: "Proper room, proper chain, clock running.",
        weights: {
          sound: { rawPolished: 0.5, minimalDense: 0.2, accessibleExperimental: -0.25 },
          skills: { versatility: 5, melody: 4 },
          psychology: { ambition: 6 },
          archetypes: { THE_HITMAKER: 3 },
          traits: { PERFECTIONIST: 2 },
        },
      },
      {
        id: "transit",
        label: "Laptop in transit.",
        detail: "Taxis, airports, whatever's open.",
        weights: {
          sound: { organicElectronic: 0.45, classicFuturistic: 0.3, minimalDense: -0.15 },
          skills: { experimentation: 5, versatility: 5 },
          psychology: { adaptability: 8 },
          archetypes: { THE_CHAMELEON: 3 },
          traits: { CHAMELEON: 3 },
        },
      },
      {
        id: "warehouse",
        label: "Dark warehouse.",
        detail: "Volume, concrete, no décor.",
        weights: {
          sound: { darkBright: -0.5, intimateAnthemic: 0.4, organicElectronic: 0.35, minimalDense: 0.25 },
          skills: { performance: 5, production: 3 },
          psychology: { riskTolerance: 6 },
          archetypes: { THE_DISRUPTOR: 2, THE_VISIONARY: 2 },
        },
      },
      {
        id: "rehearsal",
        label: "Live rehearsal room.",
        detail: "Players in the room, take after take.",
        weights: {
          sound: { organicElectronic: -0.4, rawPolished: -0.15, intimateAnthemic: 0.25 },
          skills: { performance: 8, flow: 3 },
          psychology: { resilience: 5, discipline: 4 },
          archetypes: { THE_PERFORMER: 3 },
          traits: { SHOWMAN: 3, WORKHORSE: 1 },
        },
      },
    ],
  },
  {
    id: "q_group_decisions",
    version: DISCOVERY_VERSION,
    orderIndex: 50,
    prompt: "When the group disagrees in the studio, what settles it?",
    helpText: "Groups don't fail on talent. They fail on this.",
    kind: "CHOICE",
    appliesTo: "GROUP",
    options: [
      {
        id: "best_idea",
        label: "The strongest idea wins.",
        detail: "Ego checked at the door — in theory.",
        weights: {
          sound: { accessibleExperimental: 0.15 },
          skills: { experimentation: 4, versatility: 3 },
          psychology: { adaptability: 8, ego: -5 },
          archetypes: { THE_ARCHITECT: 2 },
        },
      },
      {
        id: "originator",
        label: "Whoever started the song.",
        detail: "Authorship carries authority.",
        weights: {
          skills: { lyricism: 3, production: 3 },
          psychology: { ego: 6, discipline: 4 },
          archetypes: { THE_PURIST: 2 },
          traits: { HEADSTRONG: 3 },
        },
      },
      {
        id: "vote",
        label: "We vote.",
        detail: "Flat, fast, occasionally wrong.",
        weights: {
          sound: { accessibleExperimental: -0.2, rawPolished: 0.15 },
          skills: { versatility: 4 },
          psychology: { patience: 6, adaptability: 5, ego: -3 },
          archetypes: { THE_CHAMELEON: 2 },
        },
      },
      {
        id: "both",
        label: "We try both and pick.",
        detail: "Costs time, buys certainty.",
        weights: {
          sound: { rawPolished: 0.25 },
          skills: { production: 5 },
          psychology: { patience: 8, discipline: 6 },
          archetypes: { THE_HITMAKER: 1, THE_ARCHITECT: 1 },
          traits: { PERFECTIONIST: 3 },
        },
      },
      {
        id: "fight",
        label: "Nobody backs down — we build from the fight.",
        detail: "The friction ends up in the record.",
        weights: {
          sound: { rawPolished: -0.35, darkBright: -0.2, accessibleExperimental: 0.25 },
          skills: { battleIQ: 5, experimentation: 4 },
          psychology: { competitiveness: 9, riskTolerance: 6, patience: -5 },
          archetypes: { THE_DISRUPTOR: 3 },
          traits: { HEADSTRONG: 3 },
        },
      },
    ],
  },
  {
    id: "q_group_edge",
    version: DISCOVERY_VERSION,
    orderIndex: 60,
    prompt: "What does this group have that a solo artist can't?",
    helpText: "The reason you're doing it together.",
    kind: "CHOICE",
    appliesTo: "GROUP",
    options: [
      {
        id: "stage",
        label: "Chemistry on stage.",
        detail: "Live, it's a different animal.",
        weights: {
          sound: { intimateAnthemic: 0.4, organicElectronic: -0.2 },
          skills: { performance: 8, flow: 3 },
          psychology: { confidence: 6 },
          archetypes: { THE_PERFORMER: 3 },
          traits: { SHOWMAN: 3 },
        },
      },
      {
        id: "ideas",
        label: "A wall of ideas.",
        detail: "Four brains, one direction.",
        weights: {
          sound: { minimalDense: 0.35, accessibleExperimental: 0.25 },
          skills: { experimentation: 7, production: 4 },
          psychology: { ambition: 5 },
          archetypes: { THE_VISIONARY: 3 },
          traits: { VISIONARY: 3 },
        },
      },
      {
        id: "voices",
        label: "Range of voices.",
        detail: "Nobody can predict the next section.",
        weights: {
          sound: { melodicRhythmic: -0.2, rawPolished: 0.15 },
          skills: { versatility: 8, melody: 5 },
          psychology: { adaptability: 7 },
          archetypes: { THE_CHAMELEON: 3 },
          traits: { CHAMELEON: 3 },
        },
      },
      {
        id: "loyalty",
        label: "Loyalty.",
        detail: "Nobody leaves when it gets hard.",
        weights: {
          sound: { classicFuturistic: -0.25, intimateAnthemic: -0.15 },
          skills: { storytelling: 5, lyricism: 3 },
          psychology: { resilience: 9, discipline: 5, ego: -4 },
          archetypes: { THE_PURIST: 2, THE_STORYTELLER: 1 },
          traits: { WORKHORSE: 3 },
        },
      },
      {
        id: "output",
        label: "Volume of output.",
        detail: "We can flood the scene.",
        weights: {
          sound: { rawPolished: -0.2, accessibleExperimental: -0.15 },
          skills: { flow: 5, production: 5 },
          psychology: { discipline: 8, ambition: 6, patience: -3 },
          archetypes: { THE_HITMAKER: 2 },
          traits: { WORKHORSE: 4 },
        },
      },
    ],
  },
  {
    id: "q_statement",
    version: DISCOVERY_VERSION,
    orderIndex: 90,
    prompt: "When people hear me, I want them to ______.",
    helpText: "Your words. This becomes your creative philosophy.",
    kind: "FREE_TEXT",
    appliesTo: "SOLO",
    options: [],
  },
  {
    id: "q_statement_group",
    version: DISCOVERY_VERSION,
    orderIndex: 91,
    prompt: "When people hear us, I want them to ______.",
    helpText: "Your words. This becomes the group's creative philosophy.",
    kind: "FREE_TEXT",
    appliesTo: "GROUP",
    options: [],
  },
];
